export const DEFAULT_SCROLLING_COMMANDS: string[] = [
  "scroll up",
  "scroll down",
  "move up",
  "move down",
  "scroll to top",
  "scroll to bottom",
  "move to top",
  "move to bottom",
  "scroll to middle",
  "move to middle",
  "scroll by",
  "scroll to",
  "move by",
  "scroll by",
];
